# Generated by Django 4.0.6 on 2022-07-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, default=1, upload_to='pictures'),
            preserve_default=False,
        ),
    ]
